"""Interactive setup wizard — `kagent init`.

Hỏi provider + API key + model rồi ghi `~/.kagent/.env` với perm 0600.
"""

from pathlib import Path

import questionary
from questionary import Choice

from kagent.ui.terminal import console


CONFIG_DIR = Path.home() / ".kagent"
CONFIG_PATH = CONFIG_DIR / ".env"

GEMINI_MODELS = [
    "gemini-3.1-pro",
    "gemini-3.1-flash",
    "gemini-3.0-pro",
    "gemini-3.0-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash",
    "gemini-2.0-flash",
]

PROVIDERS = [
    ("gemini", "Gemini (Google)", "GEMINI_API_KEY", "gemini-3.1-flash", GEMINI_MODELS),
    ("openai", "OpenAI / OpenAI-compatible (Qwen, sglang, ...)", "OPENAI_API_KEY", "gpt-4o", None),
]

CUSTOM_MODEL_SENTINEL = "__custom__"


def _cancel() -> None:
    console.print("[dim]Cancelled.[/]")


def run_init_wizard() -> int:
    """Run interactive setup. Return 0 on success, 1 on cancel/error."""
    try:
        return _run_wizard()
    except (EOFError, KeyboardInterrupt):
        _cancel()
        return 1


def _run_wizard() -> int:
    console.print("[bold cyan]kagent init[/] — setup config\n")

    if CONFIG_PATH.exists():
        overwrite = questionary.confirm(
            f"Config đã tồn tại: {CONFIG_PATH}. Ghi đè?",
            default=False,
        ).ask()
        if overwrite is None:
            _cancel()
            return 1
        if not overwrite:
            console.print(f"[dim]Giữ nguyên config cũ. Edit thủ công:[/] [cyan]{CONFIG_PATH}[/]")
            return 0

    provider = questionary.select(
        "Chọn LLM provider:",
        choices=[Choice(title=label, value=key) for key, label, *_ in PROVIDERS],
    ).ask()
    if provider is None:
        _cancel()
        return 1

    _, _, key_name, default_model, model_choices = next(p for p in PROVIDERS if p[0] == provider)

    if model_choices:
        choices = [Choice(title=m, value=m) for m in model_choices]
        choices.append(Choice(title="Other (gõ tay)…", value=CUSTOM_MODEL_SENTINEL))
        model = questionary.select(
            "Chọn model:",
            choices=choices,
            default=default_model if default_model in model_choices else model_choices[0],
        ).ask()
        if model is None:
            _cancel()
            return 1
        if model == CUSTOM_MODEL_SENTINEL:
            model = questionary.text("Model name:", default=default_model).ask()
            if model is None:
                _cancel()
                return 1
    else:
        model = questionary.text("Model name:", default=default_model).ask()
        if model is None:
            _cancel()
            return 1
    model = model.strip()
    if not model:
        console.print("[red]Model name trống — abort.[/]")
        return 1

    api_key = questionary.password(f"{key_name}:").ask()
    if api_key is None:
        _cancel()
        return 1
    api_key = api_key.strip()
    if not api_key:
        console.print("[red]API key trống — abort.[/]")
        return 1

    base_url = ""
    verify_ssl = "true"
    if provider == "openai":
        base_url = (
            questionary.text(
                "OPENAI_BASE_URL (để trống nếu dùng OpenAI cloud):",
                default="",
            ).ask()
            or ""
        ).strip()
        if base_url:
            verify_ssl_ans = questionary.confirm(
                "Verify SSL cho self-hosted endpoint?",
                default=True,
            ).ask()
            if verify_ssl_ans is None:
                _cancel()
                return 1
            verify_ssl = "true" if verify_ssl_ans else "false"

    lines = [
        "# Generated by `kagent init`",
        f"LLM_PROVIDER={provider}",
        f"LLM_MODEL={model}",
        f"{key_name}={api_key}",
    ]
    if base_url:
        lines.append(f"OPENAI_BASE_URL={base_url}")
        lines.append(f"OPENAI_VERIFY_SSL={verify_ssl}")
    content = "\n".join(lines) + "\n"

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(content, encoding="utf-8")
    try:
        CONFIG_PATH.chmod(0o600)
    except OSError:
        pass

    console.print(f"\n[green]✓[/] Config saved: [cyan]{CONFIG_PATH}[/] [dim](perm 0600)[/]")
    console.print("[dim]Thử ngay:[/] [cyan]kagent[/]")
    return 0
